version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    restart: always

  loan-service:
    build:
      context: ./backend/loan-service-main
      dockerfile: ./backend/loan-service-main/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5434/loan-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - loan-service-db

  user-service-main:
    build:
      context: ./backend/user-service-main
      dockerfile: ./backend/user-service-main/Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/user-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - user-service-db



  loan-service-db:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: loan-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data_loan:/var/lib/postgresql/data


  user-service-db:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data_user:/var/lib/postgresql/data      

  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - loan-service-db
      - user-service-main
    ports:
      - 2288:80
    volumes:
      - pgadmin:/var/lib/pgadmin




volumes:
  postgres_data_user:
  pgadmin:
  postgres_data_loan: